# ------------------------------------------------------------------------------
# Develop.yml
# ------------------------------------------------------------------------------

name: Develop

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  Develop:
    name: Develop
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run './build/build.cmd'
        run: ./build/build.cmd --root ./build
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}